file=open('codingal.txt','r')
print("reading first line")
print(file.readline())
file.close()
file=open('codingal.txt','r')
print("reading multiple line")
print(file.readline())
print(file.readline())
print(file.readline())
file.close()
file=open('codingal.txt','r')
print("looping through all the line")
for line in file : 
    print(line)
file.close()